### ISSUE TITLE
UserAPI.userCreateToken doesn't return token

### ISSUE THREAD

**Issue by slonopotamus** [zeripath/java-gitea-api#4]
According to Swagger schema, `userCreateToken` returns `AccessToken`: https://github.com/zeripath/java-gitea-api/blob/master/swagger.v1.json#L11452-L11495

But in generated bindings, `userCreateToken` method is void: https://github.com/zeripath/java-gitea-api/blob/master/src/main/java/io/gitea/api/UserApi.java#L632

**Comment by zeripath** [comment]
Ugh. I'll take a look. I knew that there was something manual I had to do to the swagger JSON.

**Comment by zeripath** [comment]
I've uploaded a fixed release 1.14.0 right now - this should work on all 1.14.x versions of Gitea.

I'll pop a PR on to Gitea to fix this more permanently.

**Comment by zeripath** [comment]
We need this patch currently: https://github.com/zeripath/java-gitea-api/commit/dcfe46ca6315b918e799bf15a3c170c84ffe3321#diff-7737fa973a12da8a4c6a99b8ab264b33fcad87756116a3ba93d16292d8878651

**Comment by zeripath** [comment]
@slonopotamus do you need me to release a fixed 1.13.x?

**Comment by slonopotamus** [comment]
Yes, please, I can't upgrade due to this bug.

**Comment by slonopotamus** [comment]
Err... If you released 1.14, then it's fine, no needfor additional release.

**Comment by zeripath** [comment]
Cool. OK 1.14.0 has been released.

**Comment by slonopotamus** [comment]
I somewhat forgot about this thing and now tried to upgrade to newer java-gitea-api again.

The problem is: yes, `userCreateToken` now returns an `AccessToken` object. But. `AccessToken` only has `name` field: https://github.com/zeripath/java-gitea-api/blob/master/src/main/java/io/gitea/model/AccessToken.java#L32-L33 It doesn't have token itself. So while I can create tokens, I have no idea what token was created and thus can't pass it to API.

P.S. Also note that with modern Swagger schema (`1.16.0+dev-56-gb9a0e3323` from https://try.gitea.io/swagger.v1.json) `userCreateToken again generates with `void` return type.

**Comment by slonopotamus** [comment]
Note that back in older days, `userCreateToken` has a [working signature](https://github.com/zeripath/java-gitea-api/blob/59b3d0f054fd92b32908e5ed9af58da861181e55/src/main/java/io/gitea/api/UserApi.java#L499-L510): `AccessToken userCreateToken(String username, AccessTokenName accessTokenName)`. It accepted just token name and returned a full object that had `sha1` among other fields.

**Comment by zeripath** [comment]
ugh sorry about this!

**Comment by zeripath** [comment]
Probably need to reapply a99fa0c1492f9f52fa2009dbd5c4ecdb0a610af7 each time.

**Comment by slonopotamus** [comment]
Maybe we should report it upstream (Gitea)? I'm not an expert in Swagger, so don't actually understand why it can't properly generate `userCreateToken` signature.

**Comment by zeripath** [comment]
OK I think this should now be fixed.

In terms of opening an issue in Gitea - I'll just open a PR.

**Comment by slonopotamus** [comment]
For the record: I successfully managed to update to 1.14.0-1: https://github.com/bozaro/git-as-svn/pull/438

**Comment by zeripath** [comment]
Cool I'll close this. Sorry for missing the problem originally.

**Comment by slonopotamus** [comment]
This is broken again in 1.15.0: https://github.com/bozaro/git-as-svn/runs/3396683858#step:5:60
Do we need to apply newer Swagger schema from Gitea?

**Comment by zeripath** [comment]
Ah. I think this breakage might be because of a slight change of name and a consequent API change rather than the code being broken.

**Comment by slonopotamus** [comment]
Oh, looks like I didn't drink enough coffee yet and though that was the same problem. No worries, class rename is not a problem.

**Comment by zeripath** [comment]
Sorry for the unannounced breaking change though.
